### ISSUE TITLE
Fix late Console update about local container destruction

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2769]
For local environments, if a container is destroyed manually via CLI, information on Console is updated late.
Need to handle event immediately

**Comment by Dilshat** [comment]
How to test:
1) Create local environment with more than one container
2) Ssh into RH and destroy container manually
3) Check on Console UI, container must be removed from UI promptly

**Comment by kurmanbekova6** [comment]
Followed the steps described above:
![screenshot_2](https://user-images.githubusercontent.com/9501291/50814048-7e585c00-1342-11e9-98e9-61d6694c49f0.png)
![screenshot from 2019-01-08 12-38-39](https://user-images.githubusercontent.com/9501291/50814057-8912f100-1342-11e9-9dd5-2951d8cb09ff.png)
![screenshot_3](https://user-images.githubusercontent.com/9501291/50814064-8f08d200-1342-11e9-87a5-a696b00a8d9f.png)
Fixed in master
