### ISSUE TITLE
Handle manual bazaar container destruction

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2785]
We need to notify Bazaar when bazaar container is removed manually via subutai cli

**Comment by Dilshat** [comment]
How to test:
1. Create environment via Bazaar
2. Destroy container via `subutai destroy {container}` command
3. On Bazaar the container should get removed from host environment promptly

**Comment by kurmanbekova6** [comment]
After destroying container was removed from bazaar instantly
![screenshot from 2019-02-05 11-17-21](https://user-images.githubusercontent.com/9501291/52254446-00cf3e00-2938-11e9-8c2b-14bfdbb05393.png)
![screenshot from 2019-02-05 11-20-01](https://user-images.githubusercontent.com/9501291/52254447-00cf3e00-2938-11e9-83d0-374b9ccb7d70.png)
Fixed in master
